version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "weekly"

    ## PR Form
    default_labels:
    - "dependencies"
    commit_message:
      prefix: "Fix"
      prefix_development: "chore"
      include_scope: true
